// Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit.
pub const abi_magic: u32 = 0x4942415A;
pub const abi_major: u16 = 1;
pub const abi_minor: u16 = 24;
pub const abi_page_size: u32 = 4096;
pub const syscall_base: u16 = 64;
pub const maximum_arguments: usize = 8;
pub const maximum_argument_bytes: usize = 31;
pub const maximum_environment: usize = 8;
pub const maximum_environment_bytes: usize = 63;
pub const maximum_iovecs: usize = 8;

pub const aux_null: u64 = 0;
pub const aux_pagesz: u64 = 6;
pub const aux_uid: u64 = 11;
pub const aux_euid: u64 = 12;
pub const aux_gid: u64 = 13;
pub const aux_egid: u64 = 14;
pub const aux_secure: u64 = 23;
pub const aux_zigos_abi: u64 = 23040;
pub const aux_zigos_capabilities: u64 = 23041;

pub const seek_start: u64 = 0;
pub const seek_current: u64 = 1;
pub const seek_end: u64 = 2;
pub const message_dontwait: u64 = 1;
pub const spawn_new_process_group: u16 = @as(u16, 1) << 0;
pub const spawn_join_process_group: u16 = @as(u16, 1) << 1;
pub const spawn_pipeline_io: u16 = @as(u16, 1) << 2;
pub const spawn_foreground_process_group: u16 = @as(u16, 1) << 3;
pub const spawn_io_inherit_descriptor: u16 = 65535;
pub const wait_nohang: u64 = @as(u64, 1) << 0;
pub const wait_process_group: u64 = @as(u64, 1) << 1;
pub const directory_fd_cwd: i64 = -100;
pub const ioctl_tty_get_flags: u64 = 21505;
pub const ioctl_tty_set_flags: u64 = 21506;
pub const ioctl_tty_get_foreground_group: u64 = 21507;
pub const ioctl_tty_set_foreground_group: u64 = 21508;
pub const tty_echo: u64 = @as(u64, 1) << 0;
pub const tty_canonical: u64 = @as(u64, 1) << 1;
pub const tty_signals: u64 = @as(u64, 1) << 2;
pub const fallocate_keep_size: u64 = @as(u64, 1) << 0;
pub const fallocate_punch_hole: u64 = @as(u64, 1) << 1;
pub const mount_read_only: u64 = @as(u64, 1) << 0;
pub const filesystem_type_ramfs: u16 = 1;
pub const filesystem_type_tmpfs: u16 = 2;
pub const filesystem_type_boot_fat: u16 = 3;
pub const filesystem_type_procfs: u16 = 4;
pub const filesystem_type_devfs: u16 = 5;
pub const filesystem_type_netfs: u16 = 6;
pub const filesystem_type_zigos_persist: u16 = 7;
pub const filesystem_stat_read_only: u16 = @as(u16, 1) << 0;
pub const filesystem_stat_shared_blocks: u16 = @as(u16, 1) << 1;
pub const filesystem_stat_shared_nodes: u16 = @as(u16, 1) << 2;
pub const filesystem_stat_synthetic: u16 = @as(u16, 1) << 3;
pub const flock_shared: u64 = 1;
pub const flock_exclusive: u64 = 2;
pub const flock_nonblock: u64 = 4;
pub const flock_unlock: u64 = 8;
pub const directory_event_created: u8 = @as(u8, 1) << 0;
pub const directory_event_removed: u8 = @as(u8, 1) << 1;
pub const directory_event_rename_from: u8 = @as(u8, 1) << 2;
pub const directory_event_rename_to: u8 = @as(u8, 1) << 3;
pub const directory_event_overflow: u8 = @as(u8, 1) << 4;

pub const capability_process: u64 = @as(u64, 1) << 0;
pub const capability_descriptors: u64 = @as(u64, 1) << 1;
pub const capability_pipes: u64 = @as(u64, 1) << 2;
pub const capability_vfs: u64 = @as(u64, 1) << 3;
pub const capability_wait: u64 = @as(u64, 1) << 4;
pub const capability_virtual_memory: u64 = @as(u64, 1) << 5;
pub const capability_terminal: u64 = @as(u64, 1) << 6;
pub const capability_pseudo_files: u64 = @as(u64, 1) << 7;
pub const capability_udp_sockets: u64 = @as(u64, 1) << 8;
pub const capability_persistent_storage: u64 = @as(u64, 1) << 9;
pub const capability_normal_boot: u64 = @as(u64, 1) << 10;

pub const syscall_exit: u64 = 64;
pub const syscall_write: u64 = 65;
pub const syscall_read: u64 = 66;
pub const syscall_getpid: u64 = 67;
pub const syscall_sleep: u64 = 68;
pub const syscall_yield: u64 = 69;
pub const syscall_pipe: u64 = 70;
pub const syscall_close: u64 = 71;
pub const syscall_dup: u64 = 72;
pub const syscall_dup2: u64 = 73;
pub const syscall_open: u64 = 74;
pub const syscall_ticks: u64 = 75;
pub const syscall_spawn: u64 = 76;
pub const syscall_wait: u64 = 77;
pub const syscall_fault_return: u64 = 78;
pub const syscall_abi_query: u64 = 79;
pub const syscall_mmap: u64 = 80;
pub const syscall_munmap: u64 = 81;
pub const syscall_mprotect: u64 = 82;
pub const syscall_brk: u64 = 83;
pub const syscall_fstat: u64 = 84;
pub const syscall_getdents: u64 = 85;
pub const syscall_poll: u64 = 86;
pub const syscall_socket: u64 = 87;
pub const syscall_bind: u64 = 88;
pub const syscall_connect: u64 = 89;
pub const syscall_send: u64 = 90;
pub const syscall_recv: u64 = 91;
pub const syscall_getsockname: u64 = 92;
pub const syscall_shutdown: u64 = 93;
pub const syscall_getcwd: u64 = 94;
pub const syscall_chdir: u64 = 95;
pub const syscall_spawnv: u64 = 96;
pub const syscall_sync: u64 = 97;
pub const syscall_lseek: u64 = 98;
pub const syscall_mkdir: u64 = 99;
pub const syscall_unlink: u64 = 100;
pub const syscall_rmdir: u64 = 101;
pub const syscall_rename: u64 = 102;
pub const syscall_chmod: u64 = 103;
pub const syscall_sendto: u64 = 104;
pub const syscall_recvfrom: u64 = 105;
pub const syscall_getpeername: u64 = 106;
pub const syscall_setnonblock: u64 = 107;
pub const syscall_ioctl: u64 = 108;
pub const syscall_stat: u64 = 109;
pub const syscall_openat: u64 = 110;
pub const syscall_fsync: u64 = 111;
pub const syscall_symlink: u64 = 112;
pub const syscall_readlink: u64 = 113;
pub const syscall_link: u64 = 114;
pub const syscall_fallocate: u64 = 115;
pub const syscall_readv: u64 = 116;
pub const syscall_writev: u64 = 117;
pub const syscall_fdatasync: u64 = 118;
pub const syscall_mount: u64 = 119;
pub const syscall_umount: u64 = 120;
pub const syscall_statfs: u64 = 121;
pub const syscall_stattimes: u64 = 122;
pub const syscall_statowner: u64 = 123;
pub const syscall_umask: u64 = 124;
pub const syscall_flock: u64 = 125;
pub const syscall_lockrange: u64 = 126;
pub const syscall_watchdir: u64 = 127;

pub const errno_permission: i64 = -1;
pub const errno_not_found: i64 = -2;
pub const errno_no_process: i64 = -3;
pub const errno_interrupted: i64 = -4;
pub const errno_io: i64 = -5;
pub const errno_too_big: i64 = -7;
pub const errno_bad_fd: i64 = -9;
pub const errno_no_child: i64 = -10;
pub const errno_would_block: i64 = -11;
pub const errno_no_memory: i64 = -12;
pub const errno_access: i64 = -13;
pub const errno_fault: i64 = -14;
pub const errno_busy: i64 = -16;
pub const errno_exists: i64 = -17;
pub const errno_cross_device: i64 = -18;
pub const errno_not_directory: i64 = -20;
pub const errno_is_directory: i64 = -21;
pub const errno_invalid: i64 = -22;
pub const errno_system_file_limit: i64 = -23;
pub const errno_process_file_limit: i64 = -24;
pub const errno_file_too_large: i64 = -27;
pub const errno_no_space: i64 = -28;
pub const errno_not_seekable: i64 = -29;
pub const errno_read_only: i64 = -30;
pub const errno_broken_pipe: i64 = -32;
pub const errno_name_too_long: i64 = -36;
pub const errno_no_syscall: i64 = -38;
pub const errno_not_empty: i64 = -39;
pub const errno_loop: i64 = -40;
pub const errno_not_socket: i64 = -88;
pub const errno_address_in_use: i64 = -98;
pub const errno_not_connected: i64 = -107;
pub const errno_connection_refused: i64 = -111;

pub const syscall_count: u16 = 64;
pub const open_read: u64 = 1 << 0;
pub const open_write: u64 = 1 << 1;
pub const open_create: u64 = 1 << 2;
pub const open_truncate: u64 = 1 << 3;
pub const open_append: u64 = 1 << 4;
pub const open_close_on_exec: u64 = 1 << 5;
pub const protection_read: u64 = 1 << 0;
pub const protection_write: u64 = 1 << 1;
pub const protection_execute: u64 = 1 << 2;
pub const map_private: u64 = 1 << 0;
pub const map_anonymous: u64 = 1 << 1;
pub const map_fixed: u64 = 1 << 2;
pub const map_fixed_no_replace: u64 = 1 << 3;
pub const map_shared: u64 = 1 << 4;
pub const poll_readable: u16 = 1 << 0;
pub const poll_writable: u16 = 1 << 1;
pub const poll_error: u16 = 1 << 2;
pub const poll_hangup: u16 = 1 << 3;
pub const address_family_ipv4: u16 = 2;
pub const socket_datagram: u16 = 2;
pub const protocol_udp: u16 = 17;

pub const AbiInfo = extern struct {
    magic: u32,
    size: u16,
    major: u16,
    minor: u16,
    reserved0: u16,
    page_size: u32,
    syscall_base: u16,
    syscall_count: u16,
    reserved1: u32,
    capabilities: u64,
    user_base: u64,
    user_end: u64,
    maximum_io_bytes: u32,
    maximum_path_bytes: u32,
    maximum_processes: u16,
    maximum_descriptors: u16,
    maximum_sockets: u16,
    reserved2: u16,
};

pub const WaitStatus = extern struct {
    pid: u32,
    exit_status: u32,
    state: u32,
    fault_vector: u32,
    fault_address: u64,
};

pub const Stat = extern struct {
    node: u32,
    generation: u16,
    kind: u8,
    readonly: u8,
    mode: u16,
    mount_id: u8,
    link_count: u8,
    size: u64,
    modified_tick: u64,
};

pub const FileTimes = extern struct {
    created_tick: u64,
    modified_tick: u64,
    changed_tick: u64,
    accessed_tick: u64,
};

pub const FileOwner = extern struct {
    uid: u32,
    gid: u32,
};

pub const FilesystemStat = extern struct {
    block_size: u64,
    total_blocks: u64,
    free_blocks: u64,
    available_blocks: u64,
    total_nodes: u64,
    free_nodes: u64,
    mount_id: u32,
    filesystem_kind: u16,
    flags: u16,
    reserved: u64,
};

pub const DirectoryEntry = extern struct {
    node: u32,
    kind: u8,
    readonly: u8,
    name_length: u16,
    size: u64,
    name: [32]u8,
};

pub const PollDescriptor = extern struct {
    fd: u16,
    requested: u16,
    returned: u16,
    reserved: u16,
};

pub const DirectoryEvent = extern struct {
    sequence: u64,
    node: u32,
    generation: u16,
    kind: u8,
    flags: u8,
    name_length: u16,
    reserved0: [6]u8,
    name: [32]u8,
    reserved1: [8]u8,
};

pub const IoVector = extern struct {
    pointer: u64,
    length: u64,
};

pub const Ipv4SocketAddress = extern struct {
    family: u16,
    port_be: u16,
    address_be: u32,
};

pub const UserString = extern struct {
    pointer: u64,
    length: u16,
    reserved0: u16 = 0,
    reserved1: u32 = 0,
};

pub const SpawnRequest = extern struct {
    path_pointer: u64,
    arguments_pointer: u64,
    environment_pointer: u64,
    path_length: u16,
    argument_count: u16,
    environment_count: u16,
    flags: u16 = 0,
};

pub const AuxvEntry = extern struct {
    kind: u64,
    value: u64,
};
