/* Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit. */
#ifndef ZIGOS_H
#define ZIGOS_H

#ifndef ZIGOS_ABI_H
#define ZIGOS_ABI_H

#include <stddef.h>
#include <stdint.h>

#define ZIGOS_ABI_MAGIC UINT32_C(0x4942415A)
#define ZIGOS_ABI_MAJOR UINT16_C(1)
#define ZIGOS_ABI_MINOR UINT16_C(30)
#define ZIGOS_PAGE_SIZE UINT32_C(4096)
#define ZIGOS_SYSCALL_BASE UINT16_C(64)
#define ZIGOS_SYSCALL_COUNT UINT16_C(68)
#define ZIGOS_MAX_IOVECS UINT64_C(8)

#define ZIGOS_AUX_NULL UINT64_C(0)
#define ZIGOS_AUX_PAGESZ UINT64_C(6)
#define ZIGOS_AUX_UID UINT64_C(11)
#define ZIGOS_AUX_EUID UINT64_C(12)
#define ZIGOS_AUX_GID UINT64_C(13)
#define ZIGOS_AUX_EGID UINT64_C(14)
#define ZIGOS_AUX_SECURE UINT64_C(23)
#define ZIGOS_AUX_ZIGOS_ABI UINT64_C(23040)
#define ZIGOS_AUX_ZIGOS_CAPABILITIES UINT64_C(23041)
#define ZIGOS_SEEK_START UINT64_C(0)
#define ZIGOS_SEEK_CURRENT UINT64_C(1)
#define ZIGOS_SEEK_END UINT64_C(2)
#define ZIGOS_MSG_DONTWAIT UINT64_C(1)
#define ZIGOS_SPAWN_NEW_PROCESS_GROUP (UINT16_C(1) << 0)
#define ZIGOS_SPAWN_JOIN_PROCESS_GROUP (UINT16_C(1) << 1)
#define ZIGOS_SPAWN_PIPELINE_IO (UINT16_C(1) << 2)
#define ZIGOS_SPAWN_FOREGROUND_PROCESS_GROUP (UINT16_C(1) << 3)
#define ZIGOS_SPAWN_IO_INHERIT_DESCRIPTOR UINT16_C(65535)
#define ZIGOS_AT_CWD INT64_C(-100)
#define ZIGOS_IOCTL_TTY_GET_FLAGS UINT64_C(21505)
#define ZIGOS_IOCTL_TTY_SET_FLAGS UINT64_C(21506)
#define ZIGOS_IOCTL_TTY_GET_FOREGROUND_GROUP UINT64_C(21507)
#define ZIGOS_IOCTL_TTY_SET_FOREGROUND_GROUP UINT64_C(21508)
#define ZIGOS_TTY_ECHO (UINT64_C(1) << 0)
#define ZIGOS_TTY_CANONICAL (UINT64_C(1) << 1)
#define ZIGOS_TTY_SIGNALS (UINT64_C(1) << 2)
#define ZIGOS_FALLOCATE_KEEP_SIZE (UINT64_C(1) << 0)
#define ZIGOS_FALLOCATE_PUNCH_HOLE (UINT64_C(1) << 1)
#define ZIGOS_MOUNT_READ_ONLY (UINT64_C(1) << 0)
#define ZIGOS_FS_TYPE_RAMFS UINT16_C(1)
#define ZIGOS_FS_TYPE_TMPFS UINT16_C(2)
#define ZIGOS_FS_TYPE_BOOT_FAT UINT16_C(3)
#define ZIGOS_FS_TYPE_PROCFS UINT16_C(4)
#define ZIGOS_FS_TYPE_DEVFS UINT16_C(5)
#define ZIGOS_FS_TYPE_NETFS UINT16_C(6)
#define ZIGOS_FS_TYPE_ZIGOS_PERSIST UINT16_C(7)
#define ZIGOS_FS_STAT_READ_ONLY (UINT16_C(1) << 0)
#define ZIGOS_FS_STAT_SHARED_BLOCKS (UINT16_C(1) << 1)
#define ZIGOS_FS_STAT_SHARED_NODES (UINT16_C(1) << 2)
#define ZIGOS_FS_STAT_SYNTHETIC (UINT16_C(1) << 3)
#define ZIGOS_LOCK_SHARED UINT64_C(1)
#define ZIGOS_LOCK_EXCLUSIVE UINT64_C(2)
#define ZIGOS_LOCK_NONBLOCK UINT64_C(4)
#define ZIGOS_LOCK_UNLOCK UINT64_C(8)
#define ZIGOS_WAIT_NOHANG (UINT64_C(1) << 0)
#define ZIGOS_WAIT_PROCESS_GROUP (UINT64_C(1) << 1)
#define ZIGOS_AF_INET UINT16_C(2)
#define ZIGOS_SOCKET_STREAM UINT16_C(1)
#define ZIGOS_SOCKET_DATAGRAM UINT16_C(2)
#define ZIGOS_PROTOCOL_TCP UINT16_C(6)
#define ZIGOS_PROTOCOL_UDP UINT16_C(17)

#define ZIGOS_DIRECTORY_EVENT_CREATED (UINT8_C(1) << 0)
#define ZIGOS_DIRECTORY_EVENT_REMOVED (UINT8_C(1) << 1)
#define ZIGOS_DIRECTORY_EVENT_RENAME_FROM (UINT8_C(1) << 2)
#define ZIGOS_DIRECTORY_EVENT_RENAME_TO (UINT8_C(1) << 3)
#define ZIGOS_DIRECTORY_EVENT_OVERFLOW (UINT8_C(1) << 4)

#define ZIGOS_CAP_PROCESS (UINT64_C(1) << 0)
#define ZIGOS_CAP_DESCRIPTORS (UINT64_C(1) << 1)
#define ZIGOS_CAP_PIPES (UINT64_C(1) << 2)
#define ZIGOS_CAP_VFS (UINT64_C(1) << 3)
#define ZIGOS_CAP_WAIT (UINT64_C(1) << 4)
#define ZIGOS_CAP_VIRTUAL_MEMORY (UINT64_C(1) << 5)
#define ZIGOS_CAP_TERMINAL (UINT64_C(1) << 6)
#define ZIGOS_CAP_PSEUDO_FILES (UINT64_C(1) << 7)
#define ZIGOS_CAP_UDP_SOCKETS (UINT64_C(1) << 8)
#define ZIGOS_CAP_PERSISTENT_STORAGE (UINT64_C(1) << 9)
#define ZIGOS_CAP_NORMAL_BOOT (UINT64_C(1) << 10)
#define ZIGOS_CAP_TCP_SOCKETS (UINT64_C(1) << 11)

#define ZIGOS_SYS_EXIT UINT64_C(64)
#define ZIGOS_SYS_WRITE UINT64_C(65)
#define ZIGOS_SYS_READ UINT64_C(66)
#define ZIGOS_SYS_GETPID UINT64_C(67)
#define ZIGOS_SYS_SLEEP UINT64_C(68)
#define ZIGOS_SYS_YIELD UINT64_C(69)
#define ZIGOS_SYS_PIPE UINT64_C(70)
#define ZIGOS_SYS_CLOSE UINT64_C(71)
#define ZIGOS_SYS_DUP UINT64_C(72)
#define ZIGOS_SYS_DUP2 UINT64_C(73)
#define ZIGOS_SYS_OPEN UINT64_C(74)
#define ZIGOS_SYS_TICKS UINT64_C(75)
#define ZIGOS_SYS_SPAWN UINT64_C(76)
#define ZIGOS_SYS_WAIT UINT64_C(77)
#define ZIGOS_SYS_FAULT_RETURN UINT64_C(78)
#define ZIGOS_SYS_ABI_QUERY UINT64_C(79)
#define ZIGOS_SYS_MMAP UINT64_C(80)
#define ZIGOS_SYS_MUNMAP UINT64_C(81)
#define ZIGOS_SYS_MPROTECT UINT64_C(82)
#define ZIGOS_SYS_BRK UINT64_C(83)
#define ZIGOS_SYS_FSTAT UINT64_C(84)
#define ZIGOS_SYS_GETDENTS UINT64_C(85)
#define ZIGOS_SYS_POLL UINT64_C(86)
#define ZIGOS_SYS_SOCKET UINT64_C(87)
#define ZIGOS_SYS_BIND UINT64_C(88)
#define ZIGOS_SYS_CONNECT UINT64_C(89)
#define ZIGOS_SYS_SEND UINT64_C(90)
#define ZIGOS_SYS_RECV UINT64_C(91)
#define ZIGOS_SYS_GETSOCKNAME UINT64_C(92)
#define ZIGOS_SYS_SHUTDOWN UINT64_C(93)
#define ZIGOS_SYS_GETCWD UINT64_C(94)
#define ZIGOS_SYS_CHDIR UINT64_C(95)
#define ZIGOS_SYS_SPAWNV UINT64_C(96)
#define ZIGOS_SYS_SYNC UINT64_C(97)
#define ZIGOS_SYS_LSEEK UINT64_C(98)
#define ZIGOS_SYS_MKDIR UINT64_C(99)
#define ZIGOS_SYS_UNLINK UINT64_C(100)
#define ZIGOS_SYS_RMDIR UINT64_C(101)
#define ZIGOS_SYS_RENAME UINT64_C(102)
#define ZIGOS_SYS_CHMOD UINT64_C(103)
#define ZIGOS_SYS_SENDTO UINT64_C(104)
#define ZIGOS_SYS_RECVFROM UINT64_C(105)
#define ZIGOS_SYS_GETPEERNAME UINT64_C(106)
#define ZIGOS_SYS_SETNONBLOCK UINT64_C(107)
#define ZIGOS_SYS_IOCTL UINT64_C(108)
#define ZIGOS_SYS_STAT UINT64_C(109)
#define ZIGOS_SYS_OPENAT UINT64_C(110)
#define ZIGOS_SYS_FSYNC UINT64_C(111)
#define ZIGOS_SYS_SYMLINK UINT64_C(112)
#define ZIGOS_SYS_READLINK UINT64_C(113)
#define ZIGOS_SYS_LINK UINT64_C(114)
#define ZIGOS_SYS_FALLOCATE UINT64_C(115)
#define ZIGOS_SYS_READV UINT64_C(116)
#define ZIGOS_SYS_WRITEV UINT64_C(117)
#define ZIGOS_SYS_FDATASYNC UINT64_C(118)
#define ZIGOS_SYS_MOUNT UINT64_C(119)
#define ZIGOS_SYS_UMOUNT UINT64_C(120)
#define ZIGOS_SYS_STATFS UINT64_C(121)
#define ZIGOS_SYS_STATTIMES UINT64_C(122)
#define ZIGOS_SYS_STATOWNER UINT64_C(123)
#define ZIGOS_SYS_UMASK UINT64_C(124)
#define ZIGOS_SYS_FLOCK UINT64_C(125)
#define ZIGOS_SYS_LOCKRANGE UINT64_C(126)
#define ZIGOS_SYS_WATCHDIR UINT64_C(127)
#define ZIGOS_SYS_KILL UINT64_C(128)
#define ZIGOS_SYS_FSCHECK UINT64_C(129)
#define ZIGOS_SYS_LISTEN UINT64_C(130)
#define ZIGOS_SYS_ACCEPT UINT64_C(131)

#define ZIGOS_ERRNO_PERMISSION INT64_C(-1)
#define ZIGOS_ERRNO_NOT_FOUND INT64_C(-2)
#define ZIGOS_ERRNO_NO_PROCESS INT64_C(-3)
#define ZIGOS_ERRNO_INTERRUPTED INT64_C(-4)
#define ZIGOS_ERRNO_IO INT64_C(-5)
#define ZIGOS_ERRNO_TOO_BIG INT64_C(-7)
#define ZIGOS_ERRNO_BAD_FD INT64_C(-9)
#define ZIGOS_ERRNO_NO_CHILD INT64_C(-10)
#define ZIGOS_ERRNO_WOULD_BLOCK INT64_C(-11)
#define ZIGOS_ERRNO_NO_MEMORY INT64_C(-12)
#define ZIGOS_ERRNO_ACCESS INT64_C(-13)
#define ZIGOS_ERRNO_FAULT INT64_C(-14)
#define ZIGOS_ERRNO_BUSY INT64_C(-16)
#define ZIGOS_ERRNO_EXISTS INT64_C(-17)
#define ZIGOS_ERRNO_CROSS_DEVICE INT64_C(-18)
#define ZIGOS_ERRNO_NOT_DIRECTORY INT64_C(-20)
#define ZIGOS_ERRNO_IS_DIRECTORY INT64_C(-21)
#define ZIGOS_ERRNO_INVALID INT64_C(-22)
#define ZIGOS_ERRNO_SYSTEM_FILE_LIMIT INT64_C(-23)
#define ZIGOS_ERRNO_PROCESS_FILE_LIMIT INT64_C(-24)
#define ZIGOS_ERRNO_FILE_TOO_LARGE INT64_C(-27)
#define ZIGOS_ERRNO_NO_SPACE INT64_C(-28)
#define ZIGOS_ERRNO_NOT_SEEKABLE INT64_C(-29)
#define ZIGOS_ERRNO_READ_ONLY INT64_C(-30)
#define ZIGOS_ERRNO_BROKEN_PIPE INT64_C(-32)
#define ZIGOS_ERRNO_NAME_TOO_LONG INT64_C(-36)
#define ZIGOS_ERRNO_NO_SYSCALL INT64_C(-38)
#define ZIGOS_ERRNO_NOT_EMPTY INT64_C(-39)
#define ZIGOS_ERRNO_LOOP INT64_C(-40)
#define ZIGOS_ERRNO_NOT_SOCKET INT64_C(-88)
#define ZIGOS_ERRNO_ADDRESS_IN_USE INT64_C(-98)
#define ZIGOS_ERRNO_NOT_CONNECTED INT64_C(-107)
#define ZIGOS_ERRNO_CONNECTION_REFUSED INT64_C(-111)
#define ZIGOS_OPEN_READ (UINT64_C(1) << 0)
#define ZIGOS_OPEN_WRITE (UINT64_C(1) << 1)
#define ZIGOS_OPEN_CREATE (UINT64_C(1) << 2)
#define ZIGOS_OPEN_TRUNCATE (UINT64_C(1) << 3)
#define ZIGOS_OPEN_APPEND (UINT64_C(1) << 4)
#define ZIGOS_OPEN_CLOSE_ON_EXEC (UINT64_C(1) << 5)
#define ZIGOS_PROT_READ (UINT64_C(1) << 0)
#define ZIGOS_PROT_WRITE (UINT64_C(1) << 1)
#define ZIGOS_PROT_EXECUTE (UINT64_C(1) << 2)
#define ZIGOS_MAP_PRIVATE (UINT64_C(1) << 0)
#define ZIGOS_MAP_ANONYMOUS (UINT64_C(1) << 1)
#define ZIGOS_MAP_FIXED (UINT64_C(1) << 2)
#define ZIGOS_MAP_FIXED_NO_REPLACE (UINT64_C(1) << 3)
#define ZIGOS_MAP_SHARED (UINT64_C(1) << 4)
#define ZIGOS_POLL_READABLE (UINT16_C(1) << 0)
#define ZIGOS_POLL_WRITABLE (UINT16_C(1) << 1)
#define ZIGOS_POLL_ERROR (UINT16_C(1) << 2)
#define ZIGOS_POLL_HANGUP (UINT16_C(1) << 3)

typedef struct zigos_abi_info {
    uint32_t magic; uint16_t size; uint16_t major; uint16_t minor; uint16_t reserved0;
    uint32_t page_size; uint16_t syscall_base; uint16_t syscall_count; uint32_t reserved1;
    uint64_t capabilities; uint64_t user_base; uint64_t user_end;
    uint32_t maximum_io_bytes; uint32_t maximum_path_bytes;
    uint16_t maximum_processes; uint16_t maximum_descriptors; uint16_t maximum_sockets; uint16_t reserved2;
} zigos_abi_info;

typedef struct zigos_stat {
    uint32_t node; uint16_t generation; uint8_t kind; uint8_t readonly;
    uint16_t mode; uint8_t mount_id; uint8_t link_count; uint64_t size; uint64_t modified_tick;
} zigos_stat;

typedef struct zigos_file_times {
    uint64_t created_tick; uint64_t modified_tick; uint64_t changed_tick; uint64_t accessed_tick;
} zigos_file_times;

typedef struct zigos_file_owner { uint32_t uid; uint32_t gid; } zigos_file_owner;

typedef struct zigos_filesystem_stat {
    uint64_t block_size; uint64_t total_blocks; uint64_t free_blocks; uint64_t available_blocks;
    uint64_t total_nodes; uint64_t free_nodes; uint32_t mount_id; uint16_t filesystem_kind; uint16_t flags; uint64_t reserved;
} zigos_filesystem_stat;

typedef struct zigos_poll_descriptor {
    uint16_t fd; uint16_t requested; uint16_t returned; uint16_t reserved;
} zigos_poll_descriptor;

typedef struct zigos_directory_event {
    uint64_t sequence; uint32_t node; uint16_t generation; uint8_t kind; uint8_t flags;
    uint16_t name_length; uint8_t reserved0[6]; uint8_t name[32]; uint8_t reserved1[8];
} zigos_directory_event;

typedef struct zigos_iovec { uint64_t pointer; uint64_t length; } zigos_iovec;

typedef struct zigos_auxv_entry { uint64_t kind; uint64_t value; } zigos_auxv_entry;

typedef struct zigos_ipv4_socket_address { uint16_t family; uint16_t port_be; uint32_t address_be; } zigos_ipv4_socket_address;

_Static_assert(sizeof(zigos_abi_info) == 64, "zigos_abi_info layout");
_Static_assert(sizeof(zigos_stat) == 32, "zigos_stat layout");
_Static_assert(sizeof(zigos_file_times) == 32, "zigos_file_times layout");
_Static_assert(sizeof(zigos_file_owner) == 8, "zigos_file_owner layout");
_Static_assert(sizeof(zigos_filesystem_stat) == 64, "zigos_filesystem_stat layout");
_Static_assert(sizeof(zigos_poll_descriptor) == 8, "zigos_poll_descriptor layout");
_Static_assert(sizeof(zigos_directory_event) == 64, "zigos_directory_event layout");
_Static_assert(sizeof(zigos_iovec) == 16, "zigos_iovec layout");
_Static_assert(sizeof(zigos_ipv4_socket_address) == 8, "zigos_ipv4_socket_address layout");

#endif /* ZIGOS_ABI_H */

#ifdef __cplusplus
extern "C" {
#endif
uint64_t zigos_syscall6(uint64_t number, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5, uint64_t a6);
int64_t zigos_exit(uint32_t status);
int64_t zigos_write(uint16_t fd, const void *bytes, size_t length);
int64_t zigos_read(uint16_t fd, void *bytes, size_t length);
int64_t zigos_readv(uint16_t fd, const zigos_iovec *vectors, size_t count);
int64_t zigos_writev(uint16_t fd, const zigos_iovec *vectors, size_t count);
int64_t zigos_close(uint16_t fd);
int64_t zigos_socket(uint16_t domain, uint16_t type, uint16_t protocol);
int64_t zigos_bind(uint16_t fd, const zigos_ipv4_socket_address *address);
int64_t zigos_connect(uint16_t fd, const zigos_ipv4_socket_address *address);
int64_t zigos_listen(uint16_t fd, uint16_t backlog);
int64_t zigos_accept(uint16_t fd, zigos_ipv4_socket_address *address);
int64_t zigos_getsockname(uint16_t fd, zigos_ipv4_socket_address *address);
int64_t zigos_getpeername(uint16_t fd, zigos_ipv4_socket_address *address);
int64_t zigos_open(const char *path, uint64_t flags, uint16_t mode);
int64_t zigos_openat(int64_t directory_fd, const char *path, uint64_t flags, uint16_t mode);
int64_t zigos_fstat(uint16_t fd, zigos_stat *info);
int64_t zigos_stat_path(const char *path, zigos_stat *info);
int64_t zigos_stattimes(const char *path, zigos_file_times *times);
int64_t zigos_statowner(const char *path, zigos_file_owner *owner);
int64_t zigos_statfs(const char *path, zigos_filesystem_stat *info);
int64_t zigos_umask(uint16_t mask);
int64_t zigos_flock(uint16_t fd, uint64_t operation);
int64_t zigos_lockrange(uint16_t fd, uint64_t start, uint64_t length, uint64_t operation);
int64_t zigos_watchdir(uint16_t directory_fd);
int64_t zigos_kill(uint32_t pid, uint8_t signal);
int64_t zigos_fscheck(void);
int64_t zigos_ioctl(uint16_t fd, uint64_t request, uint64_t argument);
int64_t zigos_fsync(uint16_t fd);
int64_t zigos_fdatasync(uint16_t fd);
int64_t zigos_mount(const char *source, const char *target, const char *filesystem, uint64_t flags, const void *data);
int64_t zigos_umount(const char *target, uint64_t flags);
int64_t zigos_fallocate(uint16_t fd, uint64_t mode, uint64_t offset, uint64_t length);
int64_t zigos_mmap_file(uint64_t address, size_t length, uint64_t protection, uint64_t flags, uint16_t fd, uint64_t offset);
int64_t zigos_munmap(const void *address, size_t length);
int64_t zigos_symlink(const char *target, const char *path);
int64_t zigos_readlink(const char *path, void *bytes, size_t length);
int64_t zigos_link(const char *old_path, const char *new_path);
int64_t zigos_abi_query(zigos_abi_info *info);
uint32_t zigos_main(size_t argc, const uintptr_t *argv, const uintptr_t *envp, const zigos_auxv_entry *auxv);
#ifdef __cplusplus
}
#endif

#endif
