#!/usr/bin/env python3
"""Generate ZigOs kernel and NASM ABI constants from one versioned specification."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def zig_name(group: str, name: str) -> str:
    prefixes = {"syscalls": "syscall_", "capabilities": "capability_", "errno": "errno_"}
    return prefixes[group] + name


def generate(spec: dict) -> tuple[str, str]:
    abi = spec["abi"]
    zig: list[str] = [
        "// Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit.\n",
        f"pub const abi_magic: u32 = 0x{abi['magic']:08X};\n",
        f"pub const abi_major: u16 = {abi['major']};\n",
        f"pub const abi_minor: u16 = {abi['minor']};\n",
        f"pub const abi_page_size: u32 = {abi['page_size']};\n",
        f"pub const syscall_base: u16 = {abi['syscall_base']};\n",
    ]
    nasm: list[str] = [
        "; Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit.\n",
        f"%define ZIGOS_ABI_MAGIC 0x{abi['magic']:08X}\n",
        f"%define ZIGOS_ABI_MAJOR {abi['major']}\n",
        f"%define ZIGOS_ABI_MINOR {abi['minor']}\n",
        f"%define ZIGOS_PAGE_SIZE {abi['page_size']}\n",
    ]
    for group in ("capabilities", "syscalls", "errno"):
        zig.append("\n")
        nasm.append("\n")
        for name, value in spec[group].items():
            if group == "capabilities":
                zig.append(f"pub const {zig_name(group, name)}: u64 = @as(u64, 1) << {value};\n")
                nasm.append(f"%define ZIGOS_CAP_{name.upper()} (1 << {value})\n")
            elif group == "syscalls":
                zig.append(f"pub const {zig_name(group, name)}: u64 = {value};\n")
                nasm.append(f"%define SYS_{name.upper()} {value}\n")
            else:
                zig.append(f"pub const {zig_name(group, name)}: i64 = {value};\n")
                nasm.append(f"%define ERRNO_{name.upper()} {value}\n")
    syscall_values = list(spec["syscalls"].values())
    zig.append(f"\npub const syscall_count: u16 = {max(syscall_values) - min(syscall_values) + 1};\n")
    nasm.append(f"\n%define ZIGOS_SYSCALL_COUNT {max(syscall_values) - min(syscall_values) + 1}\n")
    return "".join(zig), "".join(nasm)


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated ABI file is stale: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.repo_root.resolve()
    spec = json.loads((root / "abi" / "zigos-abi.json").read_text(encoding="utf-8"))
    zig, nasm = generate(spec)
    write_or_check(root / "src" / "generated" / "runtime_abi_constants.zig", zig, args.check)
    write_or_check(root / "src" / "user" / "zigos_abi.inc", nasm, args.check)
    print("Verified generated ZigOs ABI constants" if args.check else "Generated ZigOs ABI constants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
