#!/usr/bin/env python3
"""Generate ZigOs kernel and NASM ABI constants from one versioned specification."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def zig_name(group: str, name: str) -> str:
    prefixes = {"syscalls": "syscall_", "capabilities": "capability_", "errno": "errno_"}
    return prefixes[group] + name


def generate(spec: dict) -> tuple[str, str, str]:
    abi = spec["abi"]
    zig: list[str] = [
        "// Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit.\n",
        f"pub const abi_magic: u32 = 0x{abi['magic']:08X};\n",
        f"pub const abi_major: u16 = {abi['major']};\n",
        f"pub const abi_minor: u16 = {abi['minor']};\n",
        f"pub const abi_page_size: u32 = {abi['page_size']};\n",
        f"pub const syscall_base: u16 = {abi['syscall_base']};\n",
    ]
    nasm: list[str] = [
        "; Generated by scripts/generate-abi.py from abi/zigos-abi.json. Do not edit.\n",
        f"%define ZIGOS_ABI_MAGIC 0x{abi['magic']:08X}\n",
        f"%define ZIGOS_ABI_MAJOR {abi['major']}\n",
        f"%define ZIGOS_ABI_MINOR {abi['minor']}\n",
        f"%define ZIGOS_PAGE_SIZE {abi['page_size']}\n",
    ]
    limits = spec["limits"]
    zig.extend([
        f"pub const maximum_arguments: usize = {limits['arguments']};\n",
        f"pub const maximum_argument_bytes: usize = {limits['argument_bytes']};\n",
        f"pub const maximum_environment: usize = {limits['environment']};\n",
        f"pub const maximum_environment_bytes: usize = {limits['environment_bytes']};\n",
    ])
    nasm.extend([
        f"%define ZIGOS_MAX_ARGUMENTS {limits['arguments']}\n",
        f"%define ZIGOS_MAX_ARGUMENT_BYTES {limits['argument_bytes']}\n",
        f"%define ZIGOS_MAX_ENVIRONMENT {limits['environment']}\n",
        f"%define ZIGOS_MAX_ENVIRONMENT_BYTES {limits['environment_bytes']}\n",
    ])
    zig.append("\n")
    nasm.append("\n")
    for name, value in spec["auxiliary_vector"].items():
        zig.append(f"pub const aux_{name}: u64 = {value};\n")
        nasm.append(f"%define ZIGOS_AUX_{name.upper()} {value}\n")
    zig.append("\n")
    nasm.append("\n")
    for name, value in spec["seek_whence"].items():
        zig.append(f"pub const seek_{name}: u64 = {value};\n")
        nasm.append(f"%define ZIGOS_SEEK_{name.upper()} {value}\n")
    for name, value in spec["message_flags"].items():
        zig.append(f"pub const message_{name}: u64 = {value};\n")
        nasm.append(f"%define ZIGOS_MSG_{name.upper()} {value}\n")
    for group in ("capabilities", "syscalls", "errno"):
        zig.append("\n")
        nasm.append("\n")
        for name, value in spec[group].items():
            if group == "capabilities":
                zig.append(f"pub const {zig_name(group, name)}: u64 = @as(u64, 1) << {value};\n")
                nasm.append(f"%define ZIGOS_CAP_{name.upper()} (1 << {value})\n")
            elif group == "syscalls":
                zig.append(f"pub const {zig_name(group, name)}: u64 = {value};\n")
                nasm.append(f"%define SYS_{name.upper()} {value}\n")
            else:
                zig.append(f"pub const {zig_name(group, name)}: i64 = {value};\n")
                nasm.append(f"%define ERRNO_{name.upper()} {value}\n")
    syscall_values = list(spec["syscalls"].values())
    zig.append(f"\npub const syscall_count: u16 = {max(syscall_values) - min(syscall_values) + 1};\n")
    nasm.append(f"\n%define ZIGOS_SYSCALL_COUNT {max(syscall_values) - min(syscall_values) + 1}\n")
    sdk = list(zig)
    sdk.extend([
        "\npub const wait_nohang: u64 = 1;\n",
        "pub const open_read: u64 = 1 << 0;\n",
        "pub const open_write: u64 = 1 << 1;\n",
        "pub const open_create: u64 = 1 << 2;\n",
        "pub const open_truncate: u64 = 1 << 3;\n",
        "pub const open_append: u64 = 1 << 4;\n",
        "pub const open_close_on_exec: u64 = 1 << 5;\n",
        "pub const protection_read: u64 = 1 << 0;\n",
        "pub const protection_write: u64 = 1 << 1;\n",
        "pub const protection_execute: u64 = 1 << 2;\n",
        "pub const map_private: u64 = 1 << 0;\n",
        "pub const map_anonymous: u64 = 1 << 1;\n",
        "pub const map_fixed: u64 = 1 << 2;\n",
        "pub const map_fixed_no_replace: u64 = 1 << 3;\n",
        "pub const poll_readable: u16 = 1 << 0;\n",
        "pub const poll_writable: u16 = 1 << 1;\n",
        "pub const poll_error: u16 = 1 << 2;\n",
        "pub const poll_hangup: u16 = 1 << 3;\n",
        "pub const address_family_ipv4: u16 = 2;\n",
        "pub const socket_datagram: u16 = 2;\n",
        "pub const protocol_udp: u16 = 17;\n",
        "\npub const AbiInfo = extern struct {\n",
        "    magic: u32,\n",
        "    size: u16,\n",
        "    major: u16,\n",
        "    minor: u16,\n",
        "    reserved0: u16,\n",
        "    page_size: u32,\n",
        "    syscall_base: u16,\n",
        "    syscall_count: u16,\n",
        "    reserved1: u32,\n",
        "    capabilities: u64,\n",
        "    user_base: u64,\n",
        "    user_end: u64,\n",
        "    maximum_io_bytes: u32,\n",
        "    maximum_path_bytes: u32,\n",
        "    maximum_processes: u16,\n",
        "    maximum_descriptors: u16,\n",
        "    maximum_sockets: u16,\n",
        "    reserved2: u16,\n",
        "};\n\n",
        "pub const WaitStatus = extern struct {\n",
        "    pid: u32,\n",
        "    exit_status: u32,\n",
        "    state: u32,\n",
        "    fault_vector: u32,\n",
        "    fault_address: u64,\n",
        "};\n\n",
        "pub const Stat = extern struct {\n",
        "    node: u32,\n",
        "    generation: u16,\n",
        "    kind: u8,\n",
        "    readonly: u8,\n",
        "    mode: u16,\n",
        "    mount_id: u8,\n",
        "    reserved0: u8,\n",
        "    size: u64,\n",
        "    modified_tick: u64,\n",
        "};\n\n",
        "pub const DirectoryEntry = extern struct {\n",
        "    node: u32,\n",
        "    kind: u8,\n",
        "    readonly: u8,\n",
        "    name_length: u16,\n",
        "    size: u64,\n",
        "    name: [32]u8,\n",
        "};\n\n",
        "pub const PollDescriptor = extern struct {\n",
        "    fd: u16,\n",
        "    requested: u16,\n",
        "    returned: u16,\n",
        "    reserved: u16,\n",
        "};\n\n",
        "pub const Ipv4SocketAddress = extern struct {\n",
        "    family: u16,\n",
        "    port_be: u16,\n",
        "    address_be: u32,\n",
        "};\n",
        "\npub const UserString = extern struct {\n",
        "    pointer: u64,\n",
        "    length: u16,\n",
        "    reserved0: u16 = 0,\n",
        "    reserved1: u32 = 0,\n",
        "};\n\n",
        "pub const SpawnRequest = extern struct {\n",
        "    path_pointer: u64,\n",
        "    arguments_pointer: u64,\n",
        "    environment_pointer: u64,\n",
        "    path_length: u16,\n",
        "    argument_count: u16,\n",
        "    environment_count: u16,\n",
        "    flags: u16 = 0,\n",
        "};\n\n",
        "pub const AuxvEntry = extern struct {\n",
        "    kind: u64,\n",
        "    value: u64,\n",
        "};\n",
    ])
    return "".join(zig), "".join(nasm), "".join(sdk)


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated ABI file is stale: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.repo_root.resolve()
    spec = json.loads((root / "abi" / "zigos-abi.json").read_text(encoding="utf-8"))
    zig, nasm, sdk = generate(spec)
    write_or_check(root / "src" / "generated" / "runtime_abi_constants.zig", zig, args.check)
    write_or_check(root / "src" / "user" / "zigos_abi.inc", nasm, args.check)
    write_or_check(root / "sdk" / "zig" / "abi.zig", sdk, args.check)
    print("Verified generated ZigOs ABI constants" if args.check else "Generated ZigOs ABI constants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
